export const hobbiesMock = [
  { value: 'acting', label: 'Acting' },
  { value: 'archery', label: 'Archery' },
  { value: 'astronomy', label: 'Astronomy' },
  { value: 'baking', label: 'Baking' },
  { value: 'basketball', label: 'Basketball' },
  { value: 'beekeeping', label: 'Beekeeping' },
  { value: 'bird_watching', label: 'Bird Watching' },
  { value: 'blogging', label: 'Blogging' },
  { value: 'board_games', label: 'Board Games' },
  { value: 'bowling', label: 'Bowling' },
  { value: 'calligraphy', label: 'Calligraphy' },
  { value: 'camping', label: 'Camping' },
  { value: 'chess', label: 'Chess' },
  { value: 'cooking', label: 'Cooking' },
  { value: 'cosplaying', label: 'Cosplaying' },
  { value: 'cycling', label: 'Cycling' },
  { value: 'dancing', label: 'Dancing' },
  { value: 'drawing', label: 'Drawing' },
  { value: 'embroidery', label: 'Embroidery' },
  { value: 'fishing', label: 'Fishing' },
  { value: 'fitness', label: 'Fitness' },
  { value: 'flower_arranging', label: 'Flower Arranging' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'gardening', label: 'Gardening' },
  { value: 'genealogy', label: 'Genealogy' },
  { value: 'glass_blowing', label: 'Glass Blowing' },
  { value: 'hiking', label: 'Hiking' },
  { value: 'horseback_riding', label: 'Horseback Riding' },
  { value: 'ice_skating', label: 'Ice Skating' },
  { value: 'jewelry_making', label: 'Jewelry Making' },
  { value: 'jigsaw_puzzles', label: 'Jigsaw Puzzles' },
  { value: 'journaling', label: 'Journaling' },
  { value: 'juggling', label: 'Juggling' },
  { value: 'karate', label: 'Karate' },
  { value: 'kayaking', label: 'Kayaking' },
  { value: 'knitting', label: 'Knitting' },
  { value: 'learning_languages', label: 'Learning Languages' },
  { value: 'magic_tricks', label: 'Magic Tricks' },
  { value: 'meditation', label: 'Meditation' },
  { value: 'model_building', label: 'Model Building' },
  { value: 'mountain_biking', label: 'Mountain Biking' },
  { value: 'origami', label: 'Origami' },
  { value: 'painting', label: 'Painting' },
  { value: 'photography', label: 'Photography' },
  { value: 'playing_guitar', label: 'Playing Guitar' },
  { value: 'playing_piano', label: 'Playing Piano' },
  { value: 'pottery', label: 'Pottery' },
  { value: 'reading', label: 'Reading' },
  { value: 'rock_climbing', label: 'Rock Climbing' },
  { value: 'running', label: 'Running' },
  { value: 'sailing', label: 'Sailing' },
  { value: 'sculpting', label: 'Sculpting' },
  { value: 'sewing', label: 'Sewing' },
  { value: 'singing', label: 'Singing' },
  { value: 'skateboarding', label: 'Skateboarding' },
  { value: 'skiing', label: 'Skiing' },
  { value: 'snowboarding', label: 'Snowboarding' },
  { value: 'surfing', label: 'Surfing' },
  { value: 'swimming', label: 'Swimming' },
  { value: 'table_tennis', label: 'Table Tennis' },
  { value: 'traveling', label: 'Traveling' },
  { value: 'video_editing', label: 'Video Editing' },
  { value: 'volleyball', label: 'Volleyball' },
  { value: 'woodworking', label: 'Woodworking' },
  { value: 'writing', label: 'Writing' },
  { value: 'yoga', label: 'Yoga' },
];
