export const countriesMock = [
  { value: 'GB', label: 'United Kingdom' },
  { value: 'US', label: 'United States' },
  { value: 'ES', label: 'Spain' },
  { value: 'FR', label: 'France' },
  { value: 'DE', label: 'Germany' },
  { value: 'IT', label: 'Italy' },
  { value: 'JP', label: 'Japan' },
  { value: 'CN', label: 'China' },
  { value: 'RU', label: 'Russia' },
  { value: 'PT', label: 'Portugal' },
  { value: 'BR', label: 'Brazil' },
  { value: 'KR', label: 'South Korea' },
  { value: 'SA', label: 'Saudi Arabia' },
  { value: 'IN', label: 'India' },
  { value: 'TR', label: 'Turkey' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'SE', label: 'Sweden' },
  { value: 'NO', label: 'Norway' },
  { value: 'DK', label: 'Denmark' },
  { value: 'FI', label: 'Finland' },
  { value: 'PL', label: 'Poland' },
  { value: 'GR', label: 'Greece' },
  { value: 'VN', label: 'Vietnam' },
  { value: 'TH', label: 'Thailand' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IR', label: 'Iran' },
  { value: 'IL', label: 'Israel' },
  { value: 'PK', label: 'Pakistan' },
  { value: 'CZ', label: 'Czech Republic' },
  { value: 'RO', label: 'Romania' },
  { value: 'HU', label: 'Hungary' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'IE', label: 'Ireland' },
  { value: 'TW', label: 'Taiwan' },
  { value: 'MX', label: 'Mexico' },
  { value: 'CA', label: 'Canada' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'AL', label: 'Albania' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AZ', label: 'Azerbaijan' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BA', label: 'Bosnia and Herzegovina' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'MM', label: 'Myanmar' },
  { value: 'HR', label: 'Croatia' },
  { value: 'EE', label: 'Estonia' },
  { value: 'GE', label: 'Georgia' },
  { value: 'IS', label: 'Iceland' },
  { value: 'KZ', label: 'Kazakhstan' },
  { value: 'KH', label: 'Cambodia' },
  { value: 'LA', label: 'Laos' },
  { value: 'LV', label: 'Latvia' },
  { value: 'LT', label: 'Lithuania' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MK', label: 'North Macedonia' },
  { value: 'MG', label: 'Madagascar' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'MT', label: 'Maltese' },
  { value: 'MN', label: 'Mongolia' },
  { value: 'NP', label: 'Nepal' },
  { value: 'PH', label: 'Philippines' },
  { value: 'SK', label: 'Slovakia' },
  { value: 'SI', label: 'Slovenia' },
  { value: 'SO', label: 'Somalia' },
  { value: 'TZ', label: 'Tanzania' },
  { value: 'TJ', label: 'Tajikistan' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'UZ', label: 'Uzbekistan' },
  { value: 'CY', label: 'Wales' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'ET', label: 'Ethiopia' },
  { value: 'PY', label: 'Paraguay' },
  { value: 'AF', label: 'Afghanistan' },
  { value: 'SN', label: 'Senegal' },
  { value: 'GH', label: 'Ghana' },
  { value: 'BE', label: 'Belgium' },
  { value: 'CL', label: 'Chile' }
];
