export const categoriesMock = [
  { value: 'Neurolinguistics', label: 'Neurolinguistics & Brain Health' },
  { value: 'Study Hacks', label: 'Study Hacks & Efficiency' },
  { value: 'Teaching', label: 'Teaching Methodology' },
  { value: 'Linguistic Curiosities', label: 'Linguistic Curiosities' },
  { value: 'Polyglot Secrets', label: 'Polyglot Secrets & Experiences' },
  { value: 'Asian Languages', label: 'Asian Languages & Culture' },
  { value: 'Russian', label: 'Russian Language & Phonetics' },
  { value: 'Linguistic Trends', label: 'Linguistic Trends & Digital Slang' },
  { value: 'Methodology', label: 'Language Learning Methodology' },
  { value: 'Technology', label: 'AI & Educational Technology' },
  { value: 'Sociolinguistics', label: 'Sociolinguistics & Dialects' },
  { value: 'Psychology', label: 'Psychology of Learning' },
  { value: 'Linguistic Anthropology', label: 'Linguistic Anthropology' },
  { value: 'Language & Career', label: 'Business & Global Career' },
  { value: 'Phonetics', label: 'Phonetics & Accent Training' },
  { value: 'Motivation', label: 'Motivation & The Plateau Effect' },
  { value: 'Culture', label: 'Cultural Concepts & Translation' },
  { value: 'Child Development', label: 'Bilingualism & Child Development' },
  { value: 'Etymology', label: 'Etymology & History of Words' },
  { value: 'Pragmatics', label: 'Social Pragmatics & Politeness' },
  { value: 'Pop Culture', label: 'Music & Pop Culture Learning' },
  { value: 'Linguistic Philosophy', label: 'Philosophy of Language' },
  { value: 'History of Language', label: 'History & Evolution of Language' },
  { value: 'Non-Verbal Communication', label: 'Non-Verbal Communication' },
  { value: 'Constructed Languages', label: 'ConLangs & Artificial Languages' },
  { value: 'Translation Studies', label: 'Translation & Literary Studies' },
  { value: 'Linguistic Psychology', label: 'Linguistic Psychology' },
  { value: 'Digital Linguistics', label: 'Digital Linguistics & Texting' },
  { value: 'Forensic Linguistics', label: 'Forensic Linguistics' },
  { value: 'Gamification', label: 'Gamification & Video Games' },
  { value: 'Lexicology', label: 'Lexicology & Loanwords' },
  { value: 'Cross-Cultural Communication', label: 'Cross-Cultural Communication' }
];